Repository DevToys-app/DevToys, pull requests merged in 2021-11, with the labels that each got.

#59 Added Guid Generator tool
  src/dev/impl/DevToys/App.xaml.cs
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Strings/cs-CZ/GuidGenerator.resw
  src/dev/impl/DevToys/Strings/en-US/GuidGenerator.resw
  src/dev/impl/DevToys/Strings/fr-FR/GuidGenerator.resw
  src/dev/impl/DevToys/Strings/ru-RU/GuidGenerator.resw
  src/dev/impl/DevToys/Themes/Custom.xaml
  src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml
  src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml.cs
  src/dev/impl/DevToys/UI/Controls/ExpandableSettingControl.xaml.cs
  src/dev/impl/DevToys/UI/Controls/ICustomTextBox.cs
  src/dev/impl/DevToys/ViewModels/Tools/GuidGenerator/GuidGeneratorToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/GuidGenerator/GuidGeneratorToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/HashGenerator/HashGeneratorToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/JsonFormatter/JsonFormatterToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/JsonYaml/JsonYamlToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/JwtDecoderEncoder/JwtDecoderEncoderToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/MarkdownPreview/MarkdownPreviewToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/RegEx/RegExToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Settings/SettingsToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/StringUtilities/StringUtilitiesToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/TextDiff/TextDiffToolProvider.cs
  src/dev/impl/DevToys/Views/Tools/GuidGenerator/GuidGeneratoToolPage.xaml
  src/dev/impl/DevToys/Views/Tools/GuidGenerator/GuidGeneratoToolPage.xaml.cs
  src/dev/impl/DevToys/Views/Tools/MarkdownPreview/MarkdownPreviewToolPage.xaml
  src/tests/DevToys.Tests/MefBaseTest.cs
  src/tests/DevToys.Tests/Providers/Tools/StringUtilitiesTests.cs
Labels: bug, enhancement

#62 Added a way to automatically offer the user to rate the app
  README.md
  src/dev/impl/DevToys/Api/Core/IMarketingService.cs
  src/dev/impl/DevToys/App.xaml.cs
  src/dev/impl/DevToys/Core/MarketingService.cs
  src/dev/impl/DevToys/Core/Threading/AsyncLazy.cs
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Models/MarketingState.cs
  src/dev/impl/DevToys/Strings/cs-CZ/MainPage.resw
  src/dev/impl/DevToys/Strings/en-US/MainPage.resw
  src/dev/impl/DevToys/Strings/fr-FR/MainPage.resw
  src/dev/impl/DevToys/Strings/ru-RU/MainPage.resw
  src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/Base64EncoderDecoder/Base64EncoderDecoderToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/GuidGenerator/GuidGeneratorToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/HashGenerator/HashGeneratorToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/JsonFormatter/JsonFormatterToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/JsonYaml/JsonYamlToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/JwtDecoderEncoder/JwtDecoderEncoderToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/MarkdownPreview/MarkdownPreviewToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/RegEx/RegExToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/StringUtilities/StringUtilitiesToolViewModel.cs
Labels: enhancement

#63 Added pl-PL translation
  src/dev/impl/DevToys/Strings/pl-PL/Base64EncoderDecoder.resw
  src/dev/impl/DevToys/Strings/pl-PL/Common.resw
  src/dev/impl/DevToys/Strings/pl-PL/GuidGenerator.resw
  src/dev/impl/DevToys/Strings/pl-PL/HashGenerator.resw
  src/dev/impl/DevToys/Strings/pl-PL/JsonFormatter.resw
  src/dev/impl/DevToys/Strings/pl-PL/JsonYaml.resw
  src/dev/impl/DevToys/Strings/pl-PL/JwtDecoderEncoder.resw
  src/dev/impl/DevToys/Strings/pl-PL/MainPage.resw
  src/dev/impl/DevToys/Strings/pl-PL/MarkdownPreview.resw
  src/dev/impl/DevToys/Strings/pl-PL/RegEx.resw
  src/dev/impl/DevToys/Strings/pl-PL/Settings.resw
  src/dev/impl/DevToys/Strings/pl-PL/StringUtilities.resw
  src/dev/impl/DevToys/Strings/pl-PL/TextDiff.resw
Labels: enhancement

#65 Added more documentation to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
