Repository DevToys-app/DevToys, pull requests merged in 2021-12, with the labels that each got.

#90 Added support of UUID version 1 in GUID Generator tool
  README.md
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Strings/cs-CZ/GuidGenerator.resw
  src/dev/impl/DevToys/Strings/en-US/GuidGenerator.resw
  src/dev/impl/DevToys/Strings/fr-FR/GuidGenerator.resw
  src/dev/impl/DevToys/Strings/pl-PL/GuidGenerator.resw
  src/dev/impl/DevToys/Strings/ru-RU/GuidGenerator.resw
  src/dev/impl/DevToys/Strings/zh-CN/GuidGenerator.resw
  src/dev/impl/DevToys/ViewModels/Tools/GuidGenerator/GuidGeneratorToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/GuidGenerator/GuidGeneratorToolViewModel.cs
  src/dev/impl/DevToys/Views/Tools/GuidGenerator/GuidGeneratorToolPage.xaml
Labels: enhancement

#91 Number Base Converter smart detection for Hexadecimal and Binary
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/Helpers/NumberBaseHelper.cs
  src/dev/impl/DevToys/ViewModels/Tools/NumberBaseConverter/NumberBaseConverterToolProvider.cs
  src/dev/impl/DevToys/Views/Tools/NumberBaseConverter/NumberBaseConverterToolPage.xaml.cs
Labels: enhancement

#95 Fixes #94 where DevToys takes several seconds to shutdown after using PNG / JPEG Compressor tool.
  src/dev/impl/DevToys.OutOfProcService/API/Core/OOP/IOutOfProcService.cs
  src/dev/impl/DevToys.OutOfProcService/Core/OOP/AppService.cs
  src/dev/impl/DevToys.OutOfProcService/OutOfProcServices/OutOfProcServiceBase.cs
  src/dev/impl/DevToys.OutOfProcService/OutOfProcServices/ShutdownService.cs
  src/dev/impl/DevToys/Api/Core/OOP/IAppService.cs
  src/dev/impl/DevToys/Core/OOP/AppService.cs
Labels: bug

#97 Fix 96 - Log Copy button failure
  src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml.cs
  src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml.cs
Labels: bug

#98 Try to reload Monaco Editor when it fails.
  src/dev/impl/DevToys.MonacoEditor/CodeEditorControl/CodeEditorCore.cs
  src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml
  src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml.cs
Labels: bug

#102 Made the main menu always collapsible.
  src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
  src/dev/impl/DevToys/Views/MainPage.xaml
Labels: enhancement

#104 Changed the tool infrastructure to make the main menu supporting tree nodes.
  src/dev/impl/DevToys/Api/Tools/IToolProviderFactory.cs
  src/dev/impl/DevToys/Api/Tools/MatchedToolProvider.cs
  src/dev/impl/DevToys/Api/Tools/ParentAttribute.cs
  src/dev/impl/DevToys/Api/Tools/ToolProviderMetadata.cs
  src/dev/impl/DevToys/Core/Collections/ExtendedObservableCollection.cs
  src/dev/impl/DevToys/Core/Collections/OrderedObservableCollection.cs
  src/dev/impl/DevToys/Core/ToolProviderFactory.cs
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Models/MatchedToolProviderViewData.cs
  src/dev/impl/DevToys/Strings/cs-CZ/ToolGroups.resw
  src/dev/impl/DevToys/Strings/en-US/ToolGroups.resw
  src/dev/impl/DevToys/Strings/fr-FR/ToolGroups.resw
  src/dev/impl/DevToys/Strings/pl-PL/ToolGroups.resw
  src/dev/impl/DevToys/Strings/ru-RU/ToolGroups.resw
  src/dev/impl/DevToys/Strings/zh-CN/ToolGroups.resw
  src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/Formatters/FormattersGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/Formatters/JsonFormatter/JsonFormatterToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/Formatters/JsonFormatter/JsonFormatterToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/TextDiff/TextDiffToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/TextDiff/TextDiffToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/TextGroupToolProvider.cs
  src/dev/impl/DevToys/Views/MainPage.xaml
  src/dev/impl/DevToys/Views/MainPage.xaml.cs
  src/tests/DevToys.Tests/Providers/IToolProviderFactoryTest.cs
  src/tests/DevToys.Tests/Providers/Tools/Base64EncoderDecoderTests.cs
Labels: enhancement

#105 Moved search results to AutoSuggestedBox instead of NavigationView
  src/dev/impl/DevToys/Api/Tools/MatchedToolProvider.cs
  src/dev/impl/DevToys/Core/Collections/ExtendedObservableCollection.cs
  src/dev/impl/DevToys/Core/ToolProviderFactory.cs
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Models/NoResultFoundMockToolProvider.cs
  src/dev/impl/DevToys/Strings/cs-CZ/MainPage.resw
  src/dev/impl/DevToys/Strings/en-US/MainPage.resw
  src/dev/impl/DevToys/Strings/fr-FR/MainPage.resw
  src/dev/impl/DevToys/Strings/pl-PL/MainPage.resw
  src/dev/impl/DevToys/Strings/ru-RU/MainPage.resw
  src/dev/impl/DevToys/Strings/zh-CN/MainPage.resw
  src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/Formatters/FormattersGroupToolProvider.cs
  src/dev/impl/DevToys/Views/MainPage.xaml
Labels: enhancement

#103 Added localized error message and error parsing for base number type
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Models/NumberBaseFormat.cs
  src/dev/impl/DevToys/Strings/cs-CZ/NumberBaseConverter.resw
  src/dev/impl/DevToys/Strings/en-US/NumberBaseConverter.resw
  src/dev/impl/DevToys/Strings/fr-FR/NumberBaseConverter.resw
  src/dev/impl/DevToys/Strings/pl-PL/NumberBaseConverter.resw
  src/dev/impl/DevToys/Strings/ru-RU/NumberBaseConverter.resw
  src/dev/impl/DevToys/Strings/zh-CN/NumberBaseConverter.resw
  src/dev/impl/DevToys/ViewModels/Tools/NumberBaseConverter/NumberBaseConverterToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/NumberBaseConverter/NumberBaseFormatter.cs
  src/tests/DevToys.Tests/Core/Formatter/BaseNumberFormatterTests.cs
Labels: bug

#108 Fixed a bug where tools orders in the grid view would change following a search.
  src/dev/impl/DevToys/Core/ToolProviderFactory.cs
Labels: bug

#109 Fixed an issue where SVG icons were flickering when the NavigationView was collapsed.
  src/dev/impl/DevToys/ViewModels/Tools/ToolProviderBase.cs
Labels: bug

#110 Added icons for the categories and rounded corners
  src/dev/impl/DevToys/Assets/Icons/Base64.svg
  src/dev/impl/DevToys/Assets/Icons/Converters.svg
  src/dev/impl/DevToys/Assets/Icons/EncodersDecoders.svg
  src/dev/impl/DevToys/Assets/Icons/JsonYaml.svg
  src/dev/impl/DevToys/Assets/Icons/TextDiff.svg
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/ViewModels/Tools/Converters/ConvertersGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/EncodersDecodersGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Formatters/FormattersGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Generators/GeneratorsGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Graphic/GraphicGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/TextGroupToolProvider.cs
Labels: enhancement

#111 Added a "All tools" menu
  src/dev/impl/DevToys/Api/Tools/IToolProviderFactory.cs
  src/dev/impl/DevToys/Api/Tools/MenuPlacement.cs
  src/dev/impl/DevToys/Api/Tools/MenuPlacementAttribute.cs
  src/dev/impl/DevToys/Api/Tools/NotSearchableAttribute.cs
  src/dev/impl/DevToys/Api/Tools/ToolProviderMetadata.cs
  src/dev/impl/DevToys/Core/ToolProviderFactory.cs
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Strings/en-US/AllTools.resw
  src/dev/impl/DevToys/UI/MainMenuNavigationViewMenuItemSelector.cs
  src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/AllTools/AllToolsToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/AllTools/AllToolsToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/GroupToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/GroupToolViewModelBase.cs
  src/dev/impl/DevToys/ViewModels/Tools/Settings/SettingsToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/ToolProviderBase.cs
  src/dev/impl/DevToys/Views/MainPage.xaml
  src/dev/impl/DevToys/Views/Tools/AllTools/AllToolsToolPage.xaml
  src/dev/impl/DevToys/Views/Tools/AllTools/AllToolsToolPage.xaml.cs
Labels: enhancement

#112 Changed the highlighting color so it uses the accent color.
  src/dev/impl/DevToys/UI/Extensions/HighlighterExtension.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/RegEx/RegExToolViewModel.cs
Labels: enhancement

#113 Show a page for search results
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Strings/cs-CZ/AllTools.resw
  src/dev/impl/DevToys/Strings/cs-CZ/SearchResult.resw
  src/dev/impl/DevToys/Strings/en-US/SearchResult.resw
  src/dev/impl/DevToys/Strings/fr-FR/AllTools.resw
  src/dev/impl/DevToys/Strings/fr-FR/SearchResult.resw
  src/dev/impl/DevToys/Strings/pl-PL/AllTools.resw
  src/dev/impl/DevToys/Strings/pl-PL/SearchResult.resw
  src/dev/impl/DevToys/Strings/ru-RU/AllTools.resw
  src/dev/impl/DevToys/Strings/ru-RU/SearchResult.resw
  src/dev/impl/DevToys/Strings/zh-CN/AllTools.resw
  src/dev/impl/DevToys/Strings/zh-CN/SearchResult.resw
  src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/GroupToolProviderBase.cs
  src/dev/impl/DevToys/ViewModels/Tools/SearchResult/SearchResultToolProvider.cs
Labels: enhancement

#114 Added support of Pin To Start + Disable Compact Overlay mode for certain tools.
  src/dev/impl/DevToys/Api/Core/IUriActivationProtocolService.cs
  src/dev/impl/DevToys/Api/Tools/NoCompactOverlaySupportAttribute.cs
  src/dev/impl/DevToys/Api/Tools/ToolProviderMetadata.cs
  src/dev/impl/DevToys/Core/UriActivationProtocolService.cs
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Messages/PinToolToStartMessage.cs
  src/dev/impl/DevToys/Strings/cs-CZ/MainPage.resw
  src/dev/impl/DevToys/Strings/en-US/MainPage.resw
  src/dev/impl/DevToys/Strings/fr-FR/MainPage.resw
  src/dev/impl/DevToys/Strings/pl-PL/MainPage.resw
  src/dev/impl/DevToys/Strings/ru-RU/MainPage.resw
  src/dev/impl/DevToys/Strings/zh-CN/MainPage.resw
  src/dev/impl/DevToys/Themes/Generic.xaml
  src/dev/impl/DevToys/UI/Controls/CustomPathIcon.cs
  src/dev/impl/DevToys/UI/Controls/ToolProvidersGridView.xaml
  src/dev/impl/DevToys/UI/Controls/ToolProvidersGridView.xaml.cs
  src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/AllTools/AllToolsToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Converters/ConvertersGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/EncodersDecodersGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Formatters/FormattersGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Generators/GeneratorsGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Graphic/GraphicGroupToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/GroupToolViewModelBase.cs
  src/dev/impl/DevToys/ViewModels/Tools/SearchResult/SearchResultToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Text/TextGroupToolProvider.cs
  src/dev/impl/DevToys/Views/MainPage.xaml
  src/dev/impl/DevToys/Views/Tools/AllTools/AllToolsToolPage.xaml
  src/dev/impl/DevToys/Views/Tools/GroupToolPage.xaml
Labels: bug, enhancement

#118 Made secondary tiles icons dynamically generated.
  assets/logo/logo-figma.fig
  src/dev/impl/DevToys/Assets/TileTemplate/SmallTile.scale-100.png
  src/dev/impl/DevToys/Assets/TileTemplate/SmallTile.scale-125.png
  src/dev/impl/DevToys/Assets/TileTemplate/SmallTile.scale-150.png
  src/dev/impl/DevToys/Assets/TileTemplate/SmallTile.scale-200.png
  src/dev/impl/DevToys/Assets/TileTemplate/SmallTile.scale-400.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square150x150Logo.scale-100.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square150x150Logo.scale-125.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square150x150Logo.scale-150.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square150x150Logo.scale-200.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square150x150Logo.scale-400.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.scale-100.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.scale-125.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.scale-150.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.scale-200.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.scale-400.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.targetsize-16.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.targetsize-24.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.targetsize-256.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.targetsize-32.png
  src/dev/impl/DevToys/Assets/TileTemplate/Square44x44Logo.targetsize-48.png
  src/dev/impl/DevToys/Core/UriActivationProtocolService.cs
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/Models/TileIconSizeDefinition.cs
  src/dev/impl/DevToys/ViewModels/Tools/ToolProviderBase.cs
Labels: enhancement

#124 Fixed blurry SVG icons
  src/dev/impl/DevToys/ViewModels/Tools/ToolProviderBase.cs
Labels: bug
