Repository DevToys-app/DevToys, pull requests merged in 2022-01, with the labels that each got.

#130 Added Lorem Ipsum Generator tool
  README.md
  THIRD-PARTY-NOTICES.md
  src/Directory.Build.props
  src/dev/impl/DevToys/Assets/Icons/LoremIpsum.svg
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Strings/cs-CZ/LoremIpsumGenerator.resw
  src/dev/impl/DevToys/Strings/en-US/LoremIpsumGenerator.resw
  src/dev/impl/DevToys/Strings/fr-FR/LoremIpsumGenerator.resw
  src/dev/impl/DevToys/Strings/pl-PL/LoremIpsumGenerator.resw
  src/dev/impl/DevToys/Strings/ru-RU/LoremIpsumGenerator.resw
  src/dev/impl/DevToys/Strings/zh-CN/LoremIpsumGenerator.resw
  src/dev/impl/DevToys/ViewModels/Tools/Generators/LoremIpsumGenerator/LoremIpsumGeneratorToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Generators/LoremIpsumGenerator/LoremIpsumGeneratorToolViewModel.cs
  src/dev/impl/DevToys/Views/Tools/LoremIpsumGenerator/LoremIpsumGeneratorToolPage.xaml
  src/dev/impl/DevToys/Views/Tools/LoremIpsumGenerator/LoremIpsumGeneratorToolPage.xaml.cs
Labels: enhancement

#169 Replaced all encoder/decoder tools dropdown with a toggle switch
  src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/Base64EncoderDecoder/Base64EncoderDecoderToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/HtmlEncoderDecoder/HtmlEncoderDecoderToolViewModel.cs
  src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/UrlEncoderDecoder/UrlEncoderDecoderToolViewModel.cs
  src/dev/impl/DevToys/Views/Tools/EncodersDecoders/Base64EncoderDecoder/Base64EncoderDecoderToolPage.xaml
  src/dev/impl/DevToys/Views/Tools/EncodersDecoders/Base64EncoderDecoder/Base64EncoderDecoderToolPage.xaml.cs
  src/dev/impl/DevToys/Views/Tools/EncodersDecoders/HtmlEncoderDecoder/HtmlEncoderDecoderToolPage.xaml
  src/dev/impl/DevToys/Views/Tools/EncodersDecoders/HtmlEncoderDecoder/HtmlEncoderDecoderToolPage.xaml.cs
  src/dev/impl/DevToys/Views/Tools/EncodersDecoders/URLEncoderDecoder/UrlEncoderDecoderToolPage.xaml
  src/dev/impl/DevToys/Views/Tools/EncodersDecoders/URLEncoderDecoder/UrlEncoderDecoderToolPage.xaml.cs
  src/tests/DevToys.Tests/Providers/Tools/Base64EncoderDecoderTests.cs
Labels: enhancement

#215 Added App Permission section to Readme
  README.md
Labels: documentation

#201 Fixed rounding errors for JSON>YAML converter
  src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/JsonYamlToolViewModel.cs
Labels: bug

#236 Fixes numbers are converted to string in Yaml to Json conversion
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/DecimalJsonConverter.cs
  src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/DecimalYamlTypeResolver.cs
  src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/JsonYamlToolViewModel.cs
Labels: bug

#276 XML Formatter
  README.md
  src/dev/impl/DevToys/Assets/Icons/HtmlEncoder.svg
  src/dev/impl/DevToys/DevToys.csproj
  src/dev/impl/DevToys/Helpers/XmlHelper.cs
  src/dev/impl/DevToys/LanguageManager.cs
  src/dev/impl/DevToys/Strings/cs-CZ/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/de-DE/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/en-US/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/es-AR/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/es-ES/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/fr-FR/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/hu-HU/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/id-ID/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/it-IT/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/ja-JP/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/pl-PL/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/pt-PT/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/ru-RU/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/zh-Hans/XmlFormatter.resw
  src/dev/impl/DevToys/Strings/zh-Hant/XmlFormatter.resw
  src/dev/impl/DevToys/ViewModels/Tools/Formatters/XmlFormatter/XmlFormatterToolProvider.cs
  src/dev/impl/DevToys/ViewModels/Tools/Formatters/XmlFormatter/XmlFormatterToolViewModel.cs
  src/dev/impl/DevToys/Views/Tools/Formatters/XmlFormatter/XmlFormatterToolPage.xaml
  src/dev/impl/DevToys/Views/Tools/Formatters/XmlFormatter/XmlFormatterToolPage.xaml.cs
  src/tests/DevToys.Tests/DevToys.Tests.csproj
  src/tests/DevToys.Tests/Helpers/XmlHelperTests.cs
Labels: enhancement

#311 Language - Same as Microsoft Windows
  src/dev/impl/DevToys/LanguageDefinition.cs
Labels: bug
